version: '3'
services:
  nuxt:
    image: typescript-nuxtjs-boilerplate
    build:
      context: "."
      dockerfile: "Dockerfile"
    env_file:
      - "docker-compose.env"
    ports:
      - 4000:4000
