version: '3'
services:
  nuxt:
    image: typescript-nuxtjs-${ENVIRONMENT}
    build:
      context: "."
      dockerfile: "Dockerfile.stg"
    environment:
      - environment=${ENVIRONMENT}
      - RUNTIME_ENV=${RUNTIME_ENV}
    ports:
     - $WEB_APP_PORT:$WEB_APP_PORT
